// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Database } from '@/types/supabase';

const supabaseUrl = "https://gouffzuetausfsbhtudy.supabase.co";
const supabaseAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvdWZmenVldGF1c2ZzYmh0dWR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNzk4MTAsImV4cCI6MjA2MTk1NTgxMH0.gmJMcKr-ZRKyCx7JixTFtJ-Jf5vU4C4qJSQsSaX_NBk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey);
